# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1aa1274efa4e5d5c16fd35c53a1e69a09bff7ebe86c8726f187a3762896771e87ca351789317458a2373dde1d6575c9f1c511494081da84b2b10ecee6744f5

test:
  secret_key_base: 14aad6f34a77f06dc925e629089df522d3940ab94c130aefb74e073abf0d29ddb3d0aa283f133a4629de7b789806f298edaf8ee59ef95e3cbde494b355f0be9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
